trigger:
- main

stages:
  - stage: Stage1
    displayName: "Stage 1"
    jobs:
      - job: Job1
        displayName: "Job 1"
        steps:
          - script: echo "Running Job 1, Step 1"
            displayName: "Job 1, Step 1"
          - script: echo "Running Job 1, Step 2"
            displayName: "Job 1, Step 2"
      - job: Job2
        displayName: "Job 2"
        steps:
          - script: echo "Running Job 2, Step 1"
            displayName: "Job 2, Step 1"
          - script: echo "Running Job 2, Step 2"
            displayName: "Job 2, Step 2"

  - stage: Stage2
    displayName: "Stage 2"
    jobs:
      - job: Job3
        displayName: "Job 3"
        steps:
          - script: echo "Running Job 3, Step 1"
            displayName: "Job 3, Step 1"
          - script: echo "Running Job 3, Step 2"
            displayName: "Job 3, Step 2"
      - job: Job4
        displayName: "Job 4"
        steps:
          - script: echo "Running Job 4, Step 1"
            displayName: "Job 4, Step 1"
          - script: echo "Running Job 4, Step 2"
            displayName: "Job 4, Step 2"